# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

  name: Build
  runs-on: ubuntu-18.04
    steps:
    - name: Set up Golang
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        clean: false
        submodules: 'recursive'
    - run: |
        git fetch --prune --unshallow --tags
    - name: Get dependencies and build
      run: |
        go install github.com/rakyll/statik
        export PATH=$PATH:~/go/bin/
        statik -src=models -f
        sudo apt-get update
        sudo apt-get -y install gcc-mingw-w64-x86-64
        sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
        sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
        chmod +x ./build.sh
        ./build.sh -r b
    - name: Upload binary files (windows_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: cloudreve_windows_amd64
        path: release/cloudreve*windows_amd64.*

    - name: Upload binary files (linux_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: cloudreve_linux_amd64
        path: release/cloudreve*linux_amd64.*

    - name: Upload binary files (linux_arm)
      uses: actions/upload-artifact@v2
      with:
        name: cloudreve_linux_arm
        path: release/cloudreve*linux_arm.*

    - name: Upload binary files (linux_arm64)
      uses: actions/upload-artifact@v2
      with:
        name: cloudreve_linux_arm64
        path: release/cloudreve*linux_arm64.*
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          clean: false
          submodules: "recursive"
      - run: |
          git fetch --prune --unshallow --tags
      - name: Get dependencies and build
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-mingw-w64-x86-64
          sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
          sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
          chmod +x ./build.sh
          ./build.sh -r b
      - name: Upload binary files (windows_386)
        uses: actions/upload-artifact@v2
        with:
          name: cloudreve_windows_386
          path: release/cloudreve*windows_386.*

      - name: Upload binary files (linux_amd64)
        uses: actions/upload-artifact@v2
        with:
          name: cloudreve_linux_amd64
          path: release/cloudreve*linux_amd64.*

      - name: Upload binary files (linux_arm)
        uses: actions/upload-artifact@v2
        with:
          name: cloudreve_linux_arm
          path: release/cloudreve*linux_arm.*

      - name: Upload binary files (linux_arm64)
        uses: actions/upload-artifact@v2
        with:
          name: cloudreve_linux_arm64
          path: release/cloudreve*linux_arm64.*
